version: '3.9'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build: ./jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - ./scripts:/home/scripts
    networks:
      - net

  remote_host:
    container_name: remote_host
    image: remote_host
    build:
      context: ./centos7
    networks:
      - net

networks:
  net: