- hosts: test1
  tasks:

    - debug:
        var: TEXT_MSG

    - debug:
        msg: "No se va a ejecutar :("
      tags: no-exec

    - debug:
        msg: "Esta linea sí se va a ejecutar :)"
      tags: si-exec
    - shell: echo $TEXT_MSG > /tmp/hola-ansible